# Generated by Django 5.2.5 on 2025-08-27 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crowd_Funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number (e.g. 01012345678).', regex='^01[0,1,2,5]\\d{8}$')]),
        ),
    ]
