# Generated by Django 5.2.5 on 2025-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crowd_Funding', '0002_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
