# Generated by Django 5.2.5 on 2025-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crowd_Funding', '0004_commentreport_projectreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='image',
            field=models.ImageField(default='project_pics/default.jpg', upload_to='project_pics/'),
        ),
    ]
