# Generated by Django 5.2.5 on 2025-08-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crowd_Funding', '0005_alter_projectpicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='project_pics/default.jpg', null=True, upload_to='user_pics/'),
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='image',
            field=models.ImageField(upload_to='project_pics/'),
        ),
    ]
